import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  ar: {
    home: 'الرئيسيه',
    correctReading: "تصحيح القراءة",
    tafseer: 'تفاسير',
    register: 'إنشاء حساب جديد',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    userProfile: 'الصفحه الشخصيه',
    welcome: 'مرحبًا بكم في منصتنا لقراءة القرآن، حيث يمكنكم بدء رحلة تحويلية من خلال النص المقدس للإسلام',
    startReading: 'بدايه قراءه',
    isReadingCorrect: 'هل قراءتك صحيحة؟ دع الذكاء الاصطناعي يخبرك!',
    uploadVoice: 'ارفع صوتك',
    allSurahs: 'جميع السور',
    showAll: 'عرض جميع السور',
    showSelected: 'عرض السور المحددة',
    notFound: 'صفحه غير موجوده',
    tafseerAlmuyasser: 'تفاسير الميسر',
    tafseerAlsaadi: 'تفاسير السعدي',
    chooseTafseer: 'اختر التفسير المناسب',
    tafseer_title: 'مساعد التفسير الذكي',
    tafseer_description: 'اكتب سؤالك أو الآية التي تريد تفسيرها واختر التفسير المناسب.',
    muyasser_title: 'تفسير الميسر',
    saadi_title: 'تفسير السعدي',
    error_occurred: 'حدث خطأ أثناء إرسال الرسالة. حاول مرة أخرى.',
    start_new_conversation: 'ابدأ محادثة جديدة',
    ai_assistant: 'مساعد التفسير الذكي',
    sample_questions_title: 'أمثلة على الأسئلة',
    sample_question_1: 'ما معنى البسملة؟',
    sample_question_2: 'فضل قراءة الفاتحة',
    sample_question_3: 'تفسير آية الكرسي',
    faq: 'الأسئلة الشائعة',
    hero_title: 'مرحباً بكم في QVRS',
    hero_subtitle: 'مشرف قراءة صوت القرآن - تصحيح تلاوة القرآن بالذكاء الاصطناعي',
    hero_description: 'نظام متقدم لتصحيح تلاوة القرآن الكريم باستخدام تقنيات الذكاء الاصطناعي المتطورة ونموذج HuBERT المُدرب مسبقاً',
    get_started: 'ابدأ الآن',
    learn_more: 'اعرف المزيد',
    about_title: "عن المنصة",
    about_description: "منصة QVRS تقدم حلولاً متقدمة لتصحيح تلاوة القرآن الكريم باستخدام الذكاء الاصطناعي.",
    about_feature1_title: "تلاوة دقيقة",
    about_feature1_desc: "تحليل دقيق لتلاوة القرآن الكريم وتقديم ملاحظات فورية.",
    about_feature2_title: "دعم صوتي",
    about_feature2_desc: "إمكانية رفع وتسجيل الصوت لتحليل التلاوة.",
    about_feature3_title: "ذكاء اصطناعي متطور",
    about_feature3_desc: "استخدام أحدث تقنيات الذكاء الاصطناعي ونموذج HuBERT.",
    about_feature4_title: "حماية وخصوصية",
    about_feature4_desc: "حماية بيانات المستخدمين وضمان الخصوصية الكاملة.",
    footer_description: "منصة QVRS تقدم حلولاً متقدمة لتصحيح تلاوة القرآن الكريم باستخدام الذكاء الاصطناعي.",
    quick_links: "روابط سريعة",
    language: "اللغة",
    all_rights_reserved: "جميع الحقوق محفوظة.",
    correct_read: "تصحيح القراءة",
    notfound_title: "الصفحة غير موجودة",
    notfound_message: "عذراً، الصفحة التي تبحث عنها غير متوفرة أو تم نقلها. يمكنك العودة إلى الصفحة الرئيسية.",
    back_home: "العودة للرئيسية",
    faq_title: "الأسئلة الشائعة",
    faq_description: "هنا تجد إجابات عن أكثر الأسئلة شيوعاً حول نظام QVRS وخدماته.",
    search_faq: "ابحث في الأسئلة...",
    contact_title: "تواصل معنا",
    faq_no_results: "لم يتم العثور على نتائج",
    faq_not_found_title: "لم تجد ما تبحث عنه؟",
    faq_not_found_desc: "تواصل معنا وسنكون سعداء لمساعدتك",
    re_record: 'إعادة',
    recording: 'التسجيل',
    listen_to_my_voice: 'الاستماع',
    to_my_voice: 'إلى صوتي',
    uploading: 'جاري رفع التسجيل...',
    upload_realtime_record: 'رفع التسجيل الصوتي الفوري',
  },
  en: {
    home: 'Home',
    correctReading: 'Correct Reading',
    tafseer: 'Tafseer',
    register: 'Register',
    login: 'Login',
    logout: 'Logout',
    userProfile: 'User Profile',
    welcome: 'Welcome to our Quran reading platform, where you can start a transformative journey through the holy text of Islam.',
    startReading: 'Start Reading',
    isReadingCorrect: 'Is your recitation correct? Let AI tell you!',
    uploadVoice: 'Upload Your Voice',
    allSurahs: 'All Surahs',
    showAll: 'Show All Surahs',
    showSelected: 'Show Selected Surahs',
    notFound: 'Page Not Found',
    tafseerAlmuyasser: 'Tafseer Al-Muyasser',
    tafseerAlsaadi: 'Tafseer Al-Saadi',
    chooseTafseer: 'Choose the appropriate Tafseer',
    tafseer_title: 'AI Tafseer Assistant',
    tafseer_description: 'Type your question or the verse you want explained and choose the appropriate tafseer.',
    muyasser_title: 'Tafseer Al-Muyasser',
    saadi_title: 'Tafseer Al-Saadi',
    error_occurred: 'An error occurred while sending the message. Please try again.',
    start_new_conversation: 'Start a new conversation',
    ai_assistant: 'AI Tafseer Assistant',
    sample_questions_title: 'Sample Questions',
    sample_question_1: 'What is the meaning of Basmala?',
    sample_question_2: 'Virtues of reciting Al-Fatiha',
    sample_question_3: 'Interpretation of Ayat al-Kursi',
    faq: 'FAQ',
    hero_title: 'Welcome to QVRS',
    hero_subtitle: 'Quran Voice Reading Supervisor - AI-powered Quran Recitation Correction',
    hero_description: 'An advanced system for correcting Quran recitation using cutting-edge artificial intelligence technologies and the pre-trained HuBERT model.',
    get_started: 'Get Started',
    learn_more: 'Learn More',
    about_title: "About the Platform",
    about_description: "QVRS offers advanced solutions for Quran recitation correction using artificial intelligence.",
    about_feature1_title: "Accurate Recitation",
    about_feature1_desc: "Precise analysis of Quran recitation with instant feedback.",
    about_feature2_title: "Voice Support",
    about_feature2_desc: "Upload and record audio for recitation analysis.",
    about_feature3_title: "Advanced AI",
    about_feature3_desc: "Utilizes cutting-edge AI technologies and the HuBERT model.",
    about_feature4_title: "Security & Privacy",
    about_feature4_desc: "User data protection and complete privacy assurance.",
    footer_description: "QVRS offers advanced solutions for Quran recitation correction using artificial intelligence.",
    quick_links: "Quick Links",
    language: "Language",
    all_rights_reserved: "All rights reserved.",
    correct_read: "Correct Reading",
    notfound_title: "Page Not Found",
    notfound_message: "Sorry, the page you are looking for does not exist or has been moved. You can return to the home page.",
    back_home: "Back to Home",
    faq_title: "Frequently Asked Questions",
    faq_description: "Find answers to the most common questions about the QVRS system and its services.",
    search_faq: "Search FAQ...",
    contact_title: "Contact Us",
    faq_no_results: "No results found",
    faq_not_found_title: "Didn't find what you're looking for?",
    faq_not_found_desc: "Contact us and we'll be happy to help you",
    re_record: 'Re-record',
    recording: 'Recording',
    listen_to_my_voice: 'Listen',
    to_my_voice: 'to my voice',
    uploading: 'Uploading...',
    upload_realtime_record: 'Upload real-time recording',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ar'); // Default is Arabic

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prevLang) => (prevLang === 'ar' ? 'en' : 'ar'));
  };

  const t = (key) => translations[language][key] || key;
  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext); 